### ISSUE TITLE
More intelligent default name

### ISSUE THREAD

**Issue by jrwagz** [jrwagz/zerg_zwo_converter#1]
Many MRC files have FILENAME set to none.

We should have the ability to fallback to either the filename or the description as the workout name in these cases.

Example MRC header

```
[COURSE HEADER]
VERSION = 0
UNITS = ENGLISH
DESCRIPTION = Sufferfest Local Hero,93,123. Created by 11407.
FILE NAME = none
MINUTES	 FTP
[END COURSE HEADER]
```

**Comment by kevinlsw** [comment]
+1

**Comment by jrwagz** [comment]
@kevinlsw this line https://github.com/jrwagz/zerg_zwo_converter/blob/master/zerg.py#L122 controls the mapping of the keynames in the MRC file, to their XML element names.  So you could easily map the description into the name by swapping these.  Although, i'm curious to know what tool was exporting the MRC file you posted here?  As I'm seeing a different format from a file that was posted to the Zwift Workouts FB group:

```
[COURSE HEADER]
VERSION = 2
UNITS = ENGLISH
DESCRIPTION = SUFFERFEST - A VERY DARK PLACE
FILE NAME = A_VERY_DARK_PLACE.MRC
MINUTES  PERCENT
[END COURSE HEADER]
[COURSE DATA]
```

**Comment by jrwagz** [comment]
Fixed
