### ISSUE TITLE
Add Support for Mid Ride Text Messages

### ISSUE THREAD

**Issue by jrwagz** [jrwagz/zerg_zwo_converter#2]
Noted in the script that there isn't support for porting over textual prompts to the rider during the ride, let's get this support rolling.

**Comment by kevinlsw** [comment]
I have added support for this in my fork.  So far I have tested only the TR workout files, and verified that the converted files work on Zwift and the messages show up fine (other than the duration and potential overlapping text issue).

The only suspicious part is the format of the COURSE TEXT entries in the MRC files.  I am going off what I see on the TR files (which may or may not be standard) which is like the following:

3300    We'll see you next time 5       0       0       72      16777215        47

First token (3300) is the absolute interval start time (seconds)
Second token is the message
Third token (5) is the duration (seconds)
Last token (47) is the time offset from the start of interval

Please send them my way if you come across other MRC files that have COURSE TEXT in there.

**Comment by jrwagz** [comment]
It's worth looking here: http://www.73summits.com/ergdb/index.php and here https://drive.google.com/folderview?id=0B4rPWl4EfyhUVEQ5WHVoOEhobU0&usp=sharing#list

Although it looks like the second folder has already been taken down.

**Comment by kevinlsw** [comment]
I checked the first one out already. Downloaded a few, but none of them
contain [COURSE TEXT].

**Comment by jrwagz** [comment]
:+1:
